#!/usr/bin/bash
# -*- coding: utf-8 -*-
echo "pal/ntsc (pal)"
read FORMAT
if [ $FORMAT ]
then
  FORMAT="NTSC"
  HIGHT="480"
fi
echo "title num (1)"
read TITLE_NUM
echo "parts"
read PARTS
echo "subtrack (0)"
read SUBTRACK
echo "audiotrack (0)"
read AUDIOTRACK
echo "title"
read TITLE
echo "year"
read YEAR
for ((i=1; i<=PARTS; i++)); do cat "${1}"VIDEO_TS/VTS_0${TITLE_NUM:-1}_$i.VOB; done | ffmpeg -fflags +genpts -probesize 250M -analyzeduration 250M -canvas_size 720x${HIGHT:-576} -i - -palette "000000, eaeaea, 000000, 000000, 828282, 828282, 828282, ffffff, 828282, bababa, 828282, 828282, 828282, 828282, 828282, 828282" -map v -map a:${AUDIOTRACK:-0} -map s:${SUBTRACK:-0} -c:v copy -c:a copy -c:s dvdsub ${TITLE}.${YEAR}.${FORMAT:-PAL}.DVD.REMUX.DD5.1.mkv
