#!/usr/bin/bash
# -*- coding: utf-8 -*-
LIBVA_DRIVER_NAME=iHD
echo "playlist:"
read PLAYLIST
if [ $PLAYLIST ]
then
  PL="-playlist $PLAYLIST"
fi
FILE=${1%.Blu*}.BluRay.HEVC.10bit.DDP5.1.mkv
if [[ $1 == *.mkv ]]
then
  INPUT=$1
else
  INPUT=bluray:"$1"
fi
echo "crop:y: (1080)"
read CH
echo "mbps: (10)"
read BITRATE
echo "audiotrack: (0)"
read AUDIOTRACK
echo "crop:x: (1920)"
read CW
ffmpeg -hwaccel qsv -hwaccel_output_format qsv -c:v h264_qsv $PL -i $INPUT -map v:0 -map a:${AUDIOTRACK:-0} -map s? -vf "vpp_qsv=cw=${CW:-1920}:ch=${CH:-1080}:format=p010" -c:v hevc_qsv -async_depth 16 -b:v ${BITRATE:-10}M -look_ahead 1 -extbrc 1 -profile:v main10 -c:a eac3 -c:s copy $FILE
