#!/usr/bin/bash

if ! [ $1 ]
then
        exit
fi

NEW_DIR=`echo $1 | sed -r -e 's/^(\w+)-([^-]+)[a-zA-Z0-9()-]+([0-9]{4}).*/\1 - \2 (\3) [WEB FLAC]/' -e 's/_/ /g'`
mkdir "$NEW_DIR"

cp $1*.jpg "$NEW_DIR"/cover.jpg
for i in $1*.flac
do
cp -l $i "$NEW_DIR"
done

cd "$NEW_DIR"
for i in *.flac
do
mv $i "`echo $i | sed -r -e 's/([0-9]+)-\w+-/\1. /' -e 's/_/ /g' -e 's/[^ _-]*/\u&/g'`"
done

cd ..
transmission-create -p -s 4096 -t https://xxx "$NEW_DIR"
