#!/bin/sh
#/etc/kernel/postinst.d/update-systemd-boot-entry
set -e

version=$1

sed -i "s/version .*/version ${version}/" /boot/loader/entries/debian.conf
sed -i "s/linux .*/linux vmlinuz-${version}/" /boot/loader/entries/debian.conf
sed -i "s/initrd .*/initrd initrd.img-${version}/" /boot/loader/entries/debian.conf
